const list = [
  {
    id: 1,
    title: "RVCA Women's Jacket",
    code: "100",
    price: 89,
    img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T2/images/I/91qs550r8EL._AC_UY500_.jpg",
    amount: 1,
  },
  {
    id: 2,
    title: "Women's Jacket",
    code: "101",
    price: 98,
    img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T2/images/I/91ovSg69hZL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 3,
    title: "Columbia Benton Hoodie ",
    code: "102",
    price: 143,
    img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T2/images/I/31x+z3QKNvL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 4,
    title: "Motherhood T-Shirts ",
    code: "103",
    price: 57,
    img: "https://m.media-amazon.com/images/I/71akufytv9L._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 5,
    title: "Short Sleeve T-Shirt ",
    code: "104",
    price: 149,
    img: "https://m.media-amazon.com/images/I/91MUDk-xdmL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "Disney Oversized Fleece",
    code: "105",
    price: 135,
    img: "https://m.media-amazon.com/images/I/81a78j0niqL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "Billie Eilish T-Shirt",
    code: "106",
    price: 693,
    img: "https://m.media-amazon.com/images/I/81CP-1qZGAS._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "Long sleeve Blouse",
    code: "107",
    price: 289,
    img: "https://m.media-amazon.com/images/I/61S9ZzNcVNL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "Short sleeve Blouse",
    code: "108",
    price: 80,
    img: "https://m.media-amazon.com/images/I/91uq6TyIhzL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 10,
    title: "Columbia women's Benton",
    code: "109",
    price: 86,
    img: "https://m.media-amazon.com/images/I/61fFoTqareS._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 11,
    title: "Columbia women's Benton",
    code: "110",
    price: 120,
    img: "https://m.media-amazon.com/images/I/81XzdFcStGL._AC_UL320_.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "Columbia suttle jacket",
    code: "111",
    price: 157,
    img: "https://m.media-amazon.com/images/I/61H2UfhG2UL._AC_UL320_.jpg",
    amount: 1,
  },
];

export default list;
